# fly.toml app configuration file generated for pogoda on 2023-06-06T22:12:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pogoda"
primary_region = "dfw"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
