# CircleCI config for Rails + webpacker
# Add env vars via CircleCI settings

version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3
  node: circleci/node@4.5.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0-node
        auth:
          username: ${DOCKERHUB_USER}
          password: ${DOCKERHUB_PASSWORD}

    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn

  test:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.0-node
        auth:
          username: ${DOCKERHUB_USER}
          password: ${DOCKERHUB_PASSWORD}
      - image: circleci/postgres:13.3
        auth:
          username: ${DOCKERHUB_USER}
          password: ${DOCKERHUB_PASSWORD}
        environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
      - image: circleci/redis:6.2.4-alpine

    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:create db:schema:load --trace

      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
