# -*- mode: fundamental -*-
# frozen_string_literal: true

module WeatherAPI
  module ResponseStub
    def response_body
      {
        "location" => {
          "name" => "Flushing",
          "region" => "New York",
          "country" => "USA",
          "lat" => 40.77,
          "lon" => -73.83,
          "tz_id" => "America/New_York",
          "localtime_epoch" => 1_670_520_944,
          "localtime" => "2022-12-08 12:35",
        },
        "current" => {
          "last_updated_epoch" => 1_670_520_600,
          "last_updated" => "2022-12-08 12:30",
          "temp_c" => 11.1,
          "temp_f" => 52.0,
          "is_day" => 1,
          "condition" => {
            "text" => "Sunny",
            "icon" => "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code" => 1000,
          },
          "wind_mph" => 13.6,
          "wind_kph" => 22.0,
          "wind_degree" => 330,
          "wind_dir" => "NNW",
          "pressure_mb" => 1023.0,
          "pressure_in" => 30.21,
          "precip_mm" => 0.0,
          "precip_in" => 0.0,
          "humidity" => 52,
          "cloud" => 0,
          "feelslike_c" => 8.7,
          "feelslike_f" => 47.6,
          "vis_km" => 16.0,
          "vis_miles" => 9.0,
          "uv" => 2.0,
          "gust_mph" => 15.2,
          "gust_kph" => 24.5,
        },
        "forecast" => {
          "forecastday" => [
            {
                "date" => "2022-12-08",
                "date_epoch" => 1_670_457_600,
                "day" => {
                    "maxtemp_c" => 11.5,
                    "maxtemp_f" => 52.7,
                    "mintemp_c" => 4.9,
                    "mintemp_f" => 40.8,
                    "avgtemp_c" => 8.2,
                    "avgtemp_f" => 46.8,
                    "maxwind_mph" => 13.2,
                    "maxwind_kph" => 21.2,
                    "totalprecip_mm" => 0.0,
                    "totalprecip_in" => 0.0,
                    "totalsnow_cm" => 0.0,
                    "avgvis_km" => 10.0,
                    "avgvis_miles" => 6.0,
                    "avghumidity" => 86.0,
                    "daily_will_it_rain" => 0,
                    "daily_chance_of_rain" => 0,
                    "daily_will_it_snow" => 0,
                    "daily_chance_of_snow" => 0,
                    "condition" => {
                        "text" => "Partly cloudy",
                        "icon" => "//cdn.weatherapi.com/weather/64x64/day/116.png",
                        "code" => 1003,
                    },
                    "uv" => 3.0,
                },
                "astro" => {},
                "hour" => [],
            },
            {
                "date" => "2022-12-09",
                "date_epoch" => 1_670_544_000,
                "day" => {
                    "maxtemp_c" => 9.8,
                    "maxtemp_f" => 49.6,
                    "mintemp_c" => -1.0,
                    "mintemp_f" => 30.2,
                    "avgtemp_c" => 2.8,
                    "avgtemp_f" => 37.1,
                    "maxwind_mph" => 12.1,
                    "maxwind_kph" => 19.4,
                    "totalprecip_mm" => 0.0,
                    "totalprecip_in" => 0.0,
                    "totalsnow_cm" => 0.0,
                    "avgvis_km" => 10.0,
                    "avgvis_miles" => 6.0,
                    "avghumidity" => 69.0,
                    "daily_will_it_rain" => 0,
                    "daily_chance_of_rain" => 0,
                    "daily_will_it_snow" => 0,
                    "daily_chance_of_snow" => 0,
                    "condition" => {
                        "text" => "Sunny",
                        "icon" => "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code" => 1000
                    },
                    "uv" => 2.0,
                },
                "astro" => {},
                "hour" => [],
            },
            {
                "date" => "2022-12-10",
                "date_epoch" => 1_670_630_400,
                "day" => {
                    "maxtemp_c" => 6.5,
                    "maxtemp_f" => 43.7,
                    "mintemp_c" => -3.2,
                    "mintemp_f" => 26.2,
                    "avgtemp_c" => 2.7,
                    "avgtemp_f" => 36.8,
                    "maxwind_mph" => 9.2,
                    "maxwind_kph" => 14.8,
                    "totalprecip_mm" => 0.0,
                    "totalprecip_in" => 0.0,
                    "totalsnow_cm" => 0.0,
                    "avgvis_km" => 10.0,
                    "avgvis_miles" => 6.0,
                    "avghumidity" => 57.0,
                    "daily_will_it_rain" => 0,
                    "daily_chance_of_rain" => 0,
                    "daily_will_it_snow" => 0,
                    "daily_chance_of_snow" => 0,
                    "condition" => {
                        "text" => "Sunny",
                        "icon" => "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code" => 1000,
                    },
                    "uv" => 2.0,
                },
                "astro" => {},
                "hour" => [],
            },
            {
                "date" => "2022-12-11",
                "date_epoch" => 1_670_716_800,
                "day" => {
                    "maxtemp_c" => 6.2,
                    "maxtemp_f" => 43.2,
                    "mintemp_c" => 0.5,
                    "mintemp_f" => 32.9,
                    "avgtemp_c" => 4.5,
                    "avgtemp_f" => 40.1,
                    "maxwind_mph" => 13.2,
                    "maxwind_kph" => 21.2,
                    "totalprecip_mm" => 4.4,
                    "totalprecip_in" => 0.17,
                    "totalsnow_cm" => 0.0,
                    "avgvis_km" => 8.3,
                    "avgvis_miles" => 5.0,
                    "avghumidity" => 81.0,
                    "daily_will_it_rain" => 1,
                    "daily_chance_of_rain" => 70,
                    "daily_will_it_snow" => 0,
                    "daily_chance_of_snow" => 0,
                    "condition" => {
                        "text" => "Patchy rain possible",
                        "icon" => "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code" => 1063,
                    },
                    "uv" => 1.0,
                },
                "astro" => {},
                "hour" => [],
            },
            {
                "date" => "2022-12-12",
                "date_epoch" => 1_670_803_200,
                "day" => {
                    "maxtemp_c" => 3.8,
                    "maxtemp_f" => 38.8,
                    "mintemp_c" => 1.0,
                    "mintemp_f" => 33.8,
                    "avgtemp_c" => 2.6,
                    "avgtemp_f" => 36.7,
                    "maxwind_mph" => 13.6,
                    "maxwind_kph" => 22.0,
                    "totalprecip_mm" => 22.3,
                    "totalprecip_in" => 0.88,
                    "totalsnow_cm" => 12.92,
                    "avgvis_km" => 6.9,
                    "avgvis_miles" => 4.0,
                    "avghumidity" => 83.0,
                    "daily_will_it_rain" => 1,
                    "daily_chance_of_rain" => 77,
                    "daily_will_it_snow" => 0,
                    "daily_chance_of_snow" => 0,
                    "condition" => {
                        "text" => "Heavy rain",
                        "icon" => "//cdn.weatherapi.com/weather/64x64/day/308.png",
                        "code" => 1195,
                    },
                    "uv" => 1.0,
                },
                "astro" => {},
                "hour" => [],
            }
          ],
        },
      }.with_indifferent_access.freeze
    end
  end
end
